#!/bin/sh
# nmcli -t connection show --active | awk -F ':' '
# /nordlynx/{vpn="vpn active"} /vpn/{name="vpn active"}
# END{if(vpn){ printf("%s\n%s\n%s\n", name, vpn, "#00FF00") } else { printf("vpn down\nvpn down\n%s\n", "#FFAE00") }}'

if [[ $(nordvpn status) == *"Connected"*  ]]; then
    echo "vpn active";
    echo "vpn active";
    echo "#00FF00";
else
    echo "vpn down";
    echo "vpn down";
    echo "#FFAE00";
fi

# mostly unedited code
#nmcli -t connection show --active | awk -F ':' '
#/tun0/{vpn="vpn active"} /vpn/{name=$1}
#END{if(vpn) printf("%s\n%s\n%s\n", name, vpn, "#00FF00")}'
